name: dev分支镜像构建
on:
  workflow_dispatch:
    inputs:
      version:
        description: '镜像标签'
        required: true
        default: 'main'  # 默认设置为 main 标签
      branch:
        description: '选择分支'
        required: true
        default: 'main'  # 默认构建 main 分支

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set version from input
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker buildx build --push \
            --platform linux/amd64 \
            --tag ghcr.io/${{ github.repository }}:${{ env.VERSION }} \
            --build-arg VERSION=${{ env.VERSION }} \
            .
        env:
          GHCR_PUBLIC: true
